---
its_ansible:
  managed: "{{ ((cmdb.Unibas_Managed  in ['managed', 'selfmanaged']) and (cmdb.Status != 'retired')) | bool }}"
  infoDir: "{{ lccms.userInfoDir }}"
  infoURL: "{{ lccms.requestURI }}/info"
  network_check_timeout: 5
  network_check_ping_target: "8.8.8.8"
