---
its_ansible:
  managed: "{{ ((cmdb.Unibas_Managed  in ['managed', 'selfmanaged']) and (cmdb.Status != 'retired')) | bool }}"
  infoDir: "{{ lccms.userInfoDir }}"
  infoURL: "{{ lccms.requestURI }}/info"
  network_check_timeout: 5
  network_check_ping_target: "8.8.8.8"
# This is from `gsettings get org.gnome.shell favorite-apps` on a newly installed Ubuntu. This is overwritten in the role.
  favorites:
    - ubuntu-desktop-bootstrap_ubuntu-desktop-bootstrap.desktop
    - firefox_firefox.desktop
    - org.gnome.Evolution.desktop
    - org.gnome.Nautilus.desktop
    - libreoffice-writer.desktop
    - org.gnome.Software.desktop
    - snap-store_snap-store.desktop
    - yelp.desktop

