---
- name: start unibas_restart_notifier_trigger path
  systemd:
    name: unibas_restart_notifier_trigger.path
    state: started

- name: start unibas_restart_notifier timer
  systemd:
    name: unibas_restart_notifier.timer
    state: started
