---
- name: "Ensure we have just the login fields on the login screen"
  lineinfile:
    path: "/etc/gdm3/greeter.dconf-defaults"
    regexp: 'disable-user-list='
    line: 'disable-user-list=true'

- name: "Copy Logo/Banner file in place"
  copy:
    src: banner_loginscreen_ubuntu.png
    dest: /usr/share/backgrounds/banner_loginscreen_ubuntu.png
    owner: root
    group: root
    mode: '0444'

- name: "Enable Logo/Banner"
  lineinfile:
    path: "/etc/gdm3/greeter.dconf-defaults"
    regexp: "logo="
    line: "logo='/usr/share/backgrounds/banner_loginscreen_ubuntu.png'"

- name: "Copy script to change background color in place"
  copy:
    src: ubuntu-gdm-set-background
    dest: /root/ubuntu-gdm-set-background
    owner: root
    group: root
    mode: '0770'

- name: "Set login screen background color to Anthrazit (ignore error)"
  command:
    cmd: "/root/ubuntu-gdm-set-background --color \\#2D373C"
    creates: /usr/local/share/gnome-shell/custom-gdm
  ignore_errors: true
