---
- name: "Check if Chrome is already installed."
  shell: |
    if command -v google-chrome >/dev/null 2>&1 || \
       command -v google-chrome-stable >/dev/null 2>&1 || \
       dpkg -l | grep -q "google-chrome"; then
      echo "installed"
    else
      echo "not_installed"
    fi
  register: chrome_check
  changed_when: false
  failed_when: false

- block:
  - name: Add Google Chrome GPG Key
    ansible.builtin.get_url:
      url: https://dl.google.com/linux/linux_signing_key.pub
      dest: /etc/apt/trusted.gpg.d/google-chrome.asc

  - name: Add Google Chrome Repo
    deb822_repository:
      name: google-chrome
      types: deb
      uris: https://dl.google.com/linux/chrome/deb/
      suites: stable
      components: main
      architectures: amd64
      signed_by: /etc/apt/trusted.gpg.d/google-chrome.asc

  - name: Install Google Chrome
    apt:
      name: "google-chrome-stable"
      state: "present"
      update_cache: yes

# To remove any old entries !!! To remove for Ubuntu 26 !!!
  - name: "Add automatic updates for Google Chrome to /etc/apt/apt.conf.d/50unattended-upgrades."
    ansible.builtin.lineinfile:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      line: '        "Google LLC:stable";'
      state: absent

  - name: Copy unattended-upgrades config
    ansible.builtin.copy:
      src: 50unattended_chrome
      dest: /etc/apt/apt.conf.d/50unattended_chrome
      owner: root
      group: root
      mode: 0644

  when:
    - global_network_available | default(false)
    - chrome_check.stdout == "not_installed"
