---
- name: Add Google Chrome GPG Key
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/trusted.gpg.d/google-chrome.asc

- name: Add Google Chrome Repo
  apt_repository:
    repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome

- name: Install Google Chrome
  apt:
    name: "google-chrome-stable"
    state: "present"
    update_cache: yes

- name: "Add automatic updates for Google Chrome to /etc/apt/apt.conf.d/50unattended-upgrades."
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    line: '        "Google LLC:stable";'
    insertafter: 'Unattended-Upgrade::Allowed-Origins {'
