---
- name: "Install polkitd-pkla package on Ubuntu < 25 because otherwise it does not work anymore."
  apt:
    name: polkitd-pkla
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('25.04', '<')

#- name: "Allow all users to change network settings"
#  copy:
#    src: org.freedesktop.NetworkManager.txt
#    dest: /etc/polkit-1/localauthority/50-local.d/org.freedesktop.NetworkManager.pkla

- name: "Copy polkit .pkla file for Ubuntu <= 24.10."
  ansible.builtin.copy:
    src: files/org.freedesktop.NetworkManager.txt
    dest: /etc/polkit-1/localauthority/50-local.d/org.freedesktop.NetworkManager.pkla
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('25.04', '<')

- name: Copy polkit .rules file for Ubuntu >= 25.04
  ansible.builtin.copy:
    src: files/50-networkmanager.rules
    dest: /etc/polkit-1/rules.d/50-networkmanager.rules
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('25.04', '>=')

# This can be used to preconfigure a WIFI connection.
- block:
  - name: "Adding WiFi definition: Ensure NetworkManager directory exists."
    ansible.builtin.file:
      path: /etc/NetworkManager/system-connections
      state: directory
      mode: '0755'

  - name: "Ensure NetworkManager connection configurations."
    ansible.builtin.template:
      src: iot_wifi.j2
      dest: "/etc/NetworkManager/system-connections/{{ item.key }}.nmconnection"
      owner: root
      group: root
      mode: '0600'
    loop: "{{ its_networking.wifi | default({}, true) | dict2items }}"
    notify:
      - reload NetworkManager

  when: (its_networking.wifi | default([], true) | length) > 0
