---
# Install the global protect VPN packages. We will install both the command line
# and the UI packages.
# This will install the system controlled service gpd.service

#- name: "Install the Global Protect UI required gnome packages."
#  ansible.builtin.apt:
#    name:
#      - gnome-shell-extension-manager
#      - gnome-shell-extension-appindicator
#      - resolvconf
#    state: present
#  when: its_globalprotect.kind == 'mobile'

- name: "Install the Global Protect UI packages."
  ansible.builtin.apt:
    deb: "{{ lccms.ansibleDir }}/roles/its/globalprotect/files/GlobalProtect_UI_focal_deb-6.1.3.0-703.deb"
    state: present
  when: its_globalprotect.kind == 'mobile'

- name: "Uninstall the Global Protect packages."
  ansible.builtin.apt:
    name: globalprotect
    state: absent
  when: its_globalprotect.kind != 'mobile'
