---
# Install the global protect VPN packages.
- block:
  - name: "Install resolvconf for GP version 6.1.3."
    ansible.builtin.apt:
      name: resolvconf
      state: present
    when: its_globalprotect.kind == 'laptop'

  - name: "Install the Global Protect APT Package."
    ansible.builtin.apt:
      name: "globalprotect"
      state: present
    when: its_globalprotect.kind == 'laptop'
  when: global_network_available | default(false)
