---
# Install the global protect VPN packages.

- name: "Install resolvconf for GP."
  ansible.builtin.apt:
    name: systemd-resolved
    state: present
  when: its_globalprotect.kind == 'mobile'

- name: "Check if the lccms repo is installed"
  stat:
    path: "/etc/apt/sources.list.d/lccms.list"
  register: lccmsrepo

- name: "Install the Global Protect APT Package."
  ansible.builtin.apt:
    name: "globalprotect"
    state: present
  when: its_globalprotect.kind == 'mobile' and lccmsrepo.stat.exists

- name: "Install the Global Protect UI packages."
  ansible.builtin.apt:
    deb: "{{ lccms.ansibleDir }}/roles/its/globalprotect/files/GlobalProtect_UI_focal_deb-6.1.3.0-703.deb"
    state: present
  when: its_globalprotect.kind == 'mobile' and not lccmsrepo.stat.exists
