---
- setup:
  register: setup_res
  tags: self-managed

- name: "Check system state. (Ignore error)"
  command: 'systemctl is-system-running'
  changed_when: false
  failed_when: false
  register: 'systemd_state'
  tags: self-managed

- name: "Report bad system state. (Ignore error)"
  fail:
    msg: "systemctl reports state {{ systemd_state.stdout }}. Please check"
  when: 'systemd_state.rc != 0'
  ignore_errors: yes
  tags: self-managed

- name: "Collect ansible, package, and shell data."
  ansible.builtin.command: "/usr/bin/dpkg -l --no-pager"
  changed_when: false
  register: package_list
  tags: self-managed

- name: "Check if admin rights are granted to any user in /home."
  command: "/bin/bash /usr/.ansible/roles/its/report/files/adrig.sh"
  register: admin_rights_granted
  changed_when: false
  tags: self-managed

- name: "Send collected data to university server: {{ its_report.server }}. (ignore error)"
  uri:
    url: "{{ its_report.server }}"
    method: POST
    body_format: form-urlencoded
    body:
      facts: "{{ setup_res|to_json }}"
      shells: "{{ lookup('file', '/etc/shells/') }}"
      packages: "{{ package_list.stdout }}"
      unit: "{{ its_report.unit }}"
      Unibas_AdminRightsGranted: "{{ admin_rights_granted.stdout }}"
      lccms_host: "{{ lccms.host }}"
    status_code: 200
  changed_when: false
  failed_when: false
  ignore_errors: yes
  tags: self-managed
