---
# We need to check if edge has already been installed some other way. If so don't do anything.
# This protects against installation if the machine was installed without lccms and them moved
# into lccms.
- block:
  - name: "Create /etc/opt/edge/policies/managed/ directory."
    file:
      path: /etc/opt/edge/policies/managed/
      state: directory
      mode: 0755
      owner: root
      group: root

#  - name: "Install Teams and Outlook PWA."
#    template:
#      src: policies.json
#      dest: /etc/opt/edge/policies/managed/policies.json
#      owner: root
#      group: root
#      mode: 0644

  - name: "Install the edge flatpak package."
    flatpak:
      name: com.microsoft.Edge
      state: present
      method: system
      remote: flathub
    when: its_edge.flatpak is true

#  - name: "Allow the edge flatpak app to see the config file"
#    command:
#      cmd: "/usr/bin/flatpak override com.microsoft.Edge --filesystem=/etc/opt/edge:ro"
#    changed_when: false

  - name: "Remove the edge flatpak package."
    flatpak:
      name: com.microsoft.Edge
      state: absent
    when: its_edge.flatpak is false

  - name: "Add the edge apt repo."
    deb822_repository:
      name: microsoft-edge
      types: deb
      uris: https://packages.microsoft.com/repos/edge/
      suites: stable
      components: main
      architectures: amd64
      signed_by: https://packages.microsoft.com/keys/microsoft.asc
    when: its_edge.apt is true

  - name: "Install the edge apt package."
    apt:
      name: microsoft-edge-stable
      state: present
      update_cache: yes
    when: its_edge.apt is true

  - name: "Remove the edge apt package."
    apt:
      name: microsoft-edge-stable
      state: absent
    when: its_edge.apt is false

  - name: "Remove the edge apt repo."
    deb822_repository:
      name: microsoft-edge
      types: deb
      uris: https://packages.microsoft.com/repos/edge/
      suites: stable
      components: main
      architectures: amd64
      signed_by: https://packages.microsoft.com/keys/microsoft.asc
      state: absent
    when: its_edge.apt is false
  when: global_network_available | default(false)
