---
- name: Create /etc/opt/edge/policies/managed/ directory
  file:
    path: /etc/opt/edge/policies/managed/
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install Teams and Outlook PWA
  template:
    src: policies.json
    dest: /etc/opt/edge/policies/managed/policies.json
    owner: root
    group: root
    mode: 0644

- name: Install the edge flatpak package
  flatpak:
    name: com.microsoft.Edge
    state: present
  when: its_edge.flatpak is true

- name: Remove the edge flatpak package
  flatpak:
    name: com.microsoft.Edge
    state: absent
  when: its_edge.flatpak is false

- name: Add repo using key from URL
  deb822_repository:
    name: microsoft-edge
    types: deb
    uris: https://packages.microsoft.com/repos/edge/
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://packages.microsoft.com/repos/edge/dists/stable/Release.gpg
  when: its_edge.apt is true

- name: Install the edge apt package
  apt:
    name: microsoft-edge-stable
    state: present
  when: its_edge.apt is true

- name: Remove the edge apt package
  apt:
    name: microsoft-edge-stable
    state: absent
  when: its_edge.apt is false

- name: Remove the edge apt repo
  deb822_repository:
    name: microsoft-edge
    types: deb
    uris: https://packages.microsoft.com/repos/edge/
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://packages.microsoft.com/repos/edge/dists/stable/Release.gpg
    state: absent
  when: its_edge.apt is false
