---
# Set up fail2ban to ward off attacks.

- name: "Ensure fail2ban is installed."
  package:
    pkg: "fail2ban"
    state: present

- name: "Deploy default settings for fail2ban jails."
  copy:
    src: "fail2ban-default.conf"
    dest: "/etc/fail2ban/jail.d/its.conf"
  notify: 'restart fail2ban'
  become: yes

- name: "Setup fail2ban to allow 10 sshd login tries (with sssd and unix login this leads to 5 tries)."
  copy:
    src: "fail2ban-sshd.conf"
    dest: "/etc/fail2ban/jail.d/its-sshd.conf"
  notify: 'restart fail2ban'

- name: "Setup fail2ban to allow 10 ssh login tries (with krb5 and unix login this leads to 5 tries)."
  copy:
    src: "fail2ban-ssh.conf"
    dest: "/etc/fail2ban/jail.d/its-sshd.conf"
  notify: 'restart fail2ban'

- name: "Make sure fail2ban is running."
  service:
    name: "fail2ban"
    state: started
    enabled: yes
