---
# In some environments, it is necessary to have only one network operational, never LAN and
# WiFi at the same time.

  - name: "Install script to allow only one network at a time."
    copy:
      src: 70-swethify.sh
      dest: /etc/NetworkManager/dispatcher.d/70-swethify.sh
      owner: root
      group: root
      mode: '0744'
    notify: 'reload NetworkManager'
