---
- name: "Clean up any dirty objects from no longer used configurations."
  debug:
    msg: "nothing to do!"
  when: not its_cleanup.execute

- name: "Remove any old ansible launcher icon."
  file:
    path: /usr/share/applications/ansible-managed.desktop
    state: "absent"

- name: "Remove update scripts."
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/opt/update_to_24.04.sh"
    - "/opt/update_to_24.04_update.sh"
    - "/etc/sudoers.d/update"

- name: "Gather package information."
  ansible.builtin.package_facts:
    manager: auto

- name: "Deinstall the Global Protect APT Package if version 6.2.1-276 is installed."
  ansible.builtin.apt:
    name: "globalprotect"
    state: absent
  when: >
    'globalprotect' in ansible_facts.packages and 
    ansible_facts.packages.globalprotect[0].version == "6.2.1-276"

- name: "Remove old APT sources files."
  file:
    path: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  with_items:
    - mozilla.list
    - google-chrome.list
    - microsoft-prod.list
    - sublime-text.list
    - docker.list
    - vscode.list

- name: "Remove old microsoft repository key."
  file:
    path: "/etc/apt/keyrings/microsoft.asc"
    state: absent

- name: "Check Microsoft GPG key format."
  ansible.builtin.command: file /usr/share/keyrings/microsoft-prod.gpg
  register: ms_gpg_file
  failed_when: false
  changed_when: false

- block:
  - name: "Remove ASCII-armored Microsoft key."
    ansible.builtin.file:
      path: /usr/share/keyrings/{{ item }}
      state: absent
    with_items:
      - microsoft-prod.gpg
      - microsoft.asc
  - name: "Remove microsoft repository."
    ansible.builtin.file:
      path: /etc/apt/sources.list.d/microsoft-prod.sources
      state: absent

  when: "'PGP public key block Public-Key (old)' in ms_gpg_file.stdout"

# Add the cleanUsers script to /usr/local/bin
- name: "Add user cleanup script."
  ansible.builtin.copy:
    src: cleanUsers.sh
    dest: /usr/local/bin/cleanUsers.sh
    owner: root
    group: root
    mode: '0550'
