---
- name: "Clean up any dirty objects from no longer used configurations."
  debug:
    msg: "nothing to do!"
  when: not its_cleanup.execute

- name: "Remove update script."
  file:
    path: "/opt/update_to_24.04.sh"
    state: absent

- name: "Remove update update script."
  file:
    path: "/opt/update_to_24.04_update.sh"
    state: absent

- name: "Remove update sudoers file."
  file:
    path: "/etc/sudoers.d/update"
    state: absent

- name: "Gather package information."
  ansible.builtin.package_facts:
    manager: auto

- name: "Deinstall the Global Protect APT Package if version 6.2.1-276 is installed."
  ansible.builtin.apt:
    name: "globalprotect"
    state: absent
  when: ansible_facts.packages.globalprotect[0].version == "6.2.1-276"
