---
- name: "Clean up any dirty objects from no longer used configurations."
  debug:
    msg: "nothing to do!"
  when: its_cleanup.execute

- name: "Remove update script"
  file:
    path: "/opt/update_to_24.04.sh"
    state: absent

- name: "Remove update update script"
  file:
    path: "/opt/update_to_24.04_update.sh"
    state: absent

- name: "Remove update sudoers file"
  file:
    path: "/etc/sudoers.d/update"
    state: absent
