---
- name: "Clean up any dirty objects from no longer used configurations."
  debug:
    msg: "nothing to do!"
  when: not its_cleanup.execute

- name: "Remove any old ansible launcher icon."
  file:
    path: /usr/share/applications/ansible-managed.desktop
    state: "absent"

- name: "Remove /etc/apt/sources.list.d/vscode.sources so it does not interfere with apt."
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/vscode.sources
    state: absent

- name: "Register a variable."
  ansible.builtin.shell: dpkg -l | grep firefox
  register: dpkg_output
  changed_when: false
  failed_when: false

- name: "Install Firefox if transitional package is present."
  ansible.builtin.shell: apt install -y firefox --allow-downgrades
  when: "'Transitional' in dpkg_output.stdout"

- name: "Retrieve the list of home directories."
  ansible.builtin.command:
    cmd: /usr/bin/ls /home
  changed_when: False
  register: home_dirs

- name: "Removes unused shares from the bookmarks of Nautilus."
  lineinfile:
    dest: /home/{{ item }}/.config/gtk-3.0/bookmarks
    line: "smb://unibasel.ads.unibas.ch/itscklb Unibas Share"
    state: absent
  loop: "{{ home_dirs.stdout_lines }}"
  ignore_errors: True

- name: "Removes unused shares from the bookmarks of Nautilus."
  lineinfile:
    dest: /home/{{ item }}/.config/gtk-3.0/bookmarks
    line: "smb://unibasel.ads.unibas.ch/itscklb/ Unibas Share"
    state: absent
  loop: "{{ home_dirs.stdout_lines }}"
  ignore_errors: True

- name: "Gather package information."
  ansible.builtin.package_facts:
    manager: auto

- name: "Deinstall the Global Protect APT Package if version 6.2.1-276 is installed."
  ansible.builtin.apt:
    name: "globalprotect"
    state: absent
  when: >
    'globalprotect' in ansible_facts.packages and
    ansible_facts.packages.globalprotect[0].version == "6.2.1-276"
