---
- name: "Download Firefox APT Keyring"
  get_url:
    url: https://packages.mozilla.org/apt/repo-signing-key.gpg
    dest: /etc/apt/keyrings/packages.mozilla.org.asc
    mode: '644'

- name: "Add Firefox Repository"
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main"
    state: present
    filename: mozilla

- name: "Copy Mozilla APT prioritization file in place"
  copy:
    src: mozilla
    dest: /etc/apt/preferences.d/mozilla
    mode: '0644'

- name: "Copy Firefox snap blocking file in place"
  copy:
    src: firefox
    dest: /etc/apt/preferences.d/block-firefox-snap
    mode: '0644'

- name: "Uninstall snap Firefox"
  snap:
    name: firefox
    state: absent
  register: firefox

- name: Purge firefox
  apt:
    name: firefox
    state: absent
  when: firefox is changed

- name: "Install Firefox package"
  apt:
    name: "firefox"
    state: "present"
    update_cache: yes
  register: firefox_apt

- name: "Adapt favorites"
  replace:
    path: "/usr/share/glib-2.0/schemas/10_ubuntu-settings.gschema.override"
    regexp: 'firefox_firefox.desktop'
    replace: 'firefox.desktop'

- name: "Compile schemas"
  command: "/usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/"