---
# We need to check if a non snap version was already installed. If so, we should not do anything.
- block:
  - name: "Download Firefox APT Keyring."
    get_url:
      url: https://packages.mozilla.org/apt/repo-signing-key.gpg
      dest: /usr/share/keyrings/packages.mozilla.org.asc
      mode: '644'

  - name: "Add Firefox Repository."
    deb822_repository:
      name: mozilla
      types: deb
      uris: https://packages.mozilla.org/apt
      suites: mozilla
      components: main
      signed_by: /usr/share/keyrings/packages.mozilla.org.asc

  - name: "Copy Mozilla APT prioritization file in place."
    copy:
      src: mozilla
      dest: /etc/apt/preferences.d/mozilla
      mode: '0644'

  - name: "Uninstall snap Firefox."
    snap:
      name: firefox
      state: absent
    register: firefox

  - name: "Purge any old firefox if snap was removed."
    apt:
      name: firefox
      state: absent
    when: firefox is changed

  - name: "Install Firefox package."
    apt:
      name: "firefox"
      state: "present"
      update_cache: yes
    register: firefox_apt

  - name: "Replace or add to favorites if not already done."
    set_fact:
      its_ansible: "{{ its_ansible | combine({
        'favorites':
          ('firefox_firefox.desktop' in its_ansible.favorites) | ternary(
            its_ansible.favorites | map('regex_replace', '^firefox_firefox\\.desktop$', 'firefox.desktop') | list,
            (its_ansible.favorites + ['firefox.desktop'])
            if 'firefox.desktop' not in its_ansible.favorites
            else its_ansible.favorites
          )
      }, recursive=True) }}"
    when: firefox_apt is changed
  
  when: global_network_available | default(false)
