---
- name: "Installing SSSD and Kerberos dependencies."
  apt:
      name: sssd, libpam-sss, libnss-sss, adcli, krb5-user, sssd-dbus
      state: present
  when: its_adbind.needAD

- name: "Joining AD."
  command: /bin/bash -c "echo -n oO1DMWGQdDDXTW9Vb6lQQVIIL | /usr/sbin/adcli join -U d-cs-adbindl --stdin-password UNIBASEL.ADS.UNIBAS.CH"
  args:
      creates: /etc/krb5.keytab
  notify:
  - restart sssd
  when: its_adbind.needAD
