---
- name: "Set the actual hostname to that recorded in the management system."
  ansible.builtin.hostname:
    name: "{{ its_fqdn.name }}"
  tags: self-managed

## May be necessary, check it out and replace actual_hostname!
## * On a mobile device, ensure we have a 127.0.0.1 entry to a working greeter
##- name: "its.setfqdn: Set an entry for the 127.0.0.1 address."
##  lineinfile:
##    path: "/etc/hosts"
##    regexp: '^127\.0\.1\.1'
##    line: "127.0.1.1    {{ its_fqdn.name }} {{ actual_hostname }}"
##    insertafter: '^127\.0\.0\.1'
##    state: present
##  when: "{{ its_fqdn.kind }} == 'mobile'"
