---
# Simply install the user scripts to set the password.
- name: "Install utility programs to set the user disk encryption password."
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: "sudo_cryptsetup", dst: "/etc/sudoers.d/cryptsetup", mode: "u=rw,g=r,o-rwx" }
    - { src: "diskkey",         dst: "/usr/sbin/diskkey",         mode: "u=rwx,g=rx,o=rx"}

