---
parameters:
  its_firewall:
    state:
      type: choice
      default: 'block'
      comment: The forced state of the firewall. This still allows adding or removing rules as needed.
      options:
      - label: Block
        value: 'block'
        comment: Block all incoming traffic not listed, allow all outgoing.
      - label: Allow
        value: 'allow'
        comment: Allow all traffic.
    apps:
      type: list
      default: []
      comment: The array of application names for which to allow incoming traffic.
